recipe_creation:
  description: >
    À partir du titre de recette "{recipe_name}", élaborer une recette
    détaillée avec ingrédients, proportions et instructions précises pour une
    famille de 2 adultes et un enfant de 10 ans. La recette doit être
    délicieuse, accessible et présenter une touche créative qui rendra le plat
    attrayant pour un enfant sans sacrifier le goût pour les adultes.
  expected_output: >
    Une recette complète avec liste d'ingrédients (avec quantités), temps de
    préparation, temps de cuisson, niveau de difficulté, et instructions
    détaillées étape par étape, sans '```'.
  agent: recipe_expert

thermomix_adaptation:
  description: >
    Adapter la recette pour utilisation avec un Thermomix. La recette est
    basée sur ce plat : {recipe_name}   
    Fournir des instructions claires pour chaque étape, en indiquant les
    paramètres précis (vitesse, température, durée) pour le Thermomix.
  expected_output: >
    Version Thermomix de la recette avec paramètres précis pour chaque étape,
    maintenant toutes les saveurs et la qualité de la recette originale, sans '```'.
  agent: thermomix_adapter

nutrition_evaluation:
  description: >
    Évaluer le profil nutritionnel de la recette pour : {recipe_name} 
    Identifier les points forts et les améliorations possibles du point de vue nutritionnel,
    particulièrement en considérant qu'elle sera servie à un enfant de 10 ans.
  expected_output: >
    Analyse nutritionnelle de la recette avec valeurs approximatives
    (calories, macronutriments), points forts nutritionnels, et 2-3
    suggestions concrètes d'amélioration sans compromettre le goût, sans '```'.
  agent: nutritionist

recipe_integration:
  description: >
    Intégrer des suggestions nutritionnelles à la recette Thermomix pour 
    {recipe_name}, tout en préservant la saveur et la facilité de préparation.
    Proposer des améliorations nutritionnelles adaptées aux enfants.
  expected_output: >
    Version améliorée de la recette Thermomix intégrant les suggestions
    nutritionnelles, avec les modifications clairement indiquées, sans '```'.
  agent: recipe_expert

html_creation:
  description: >
    Créer une version HTML élégante et bien structurée de la recette finale
    pour {recipe_name}. La présentation doit être professionnelle, facile à lire,
    avec des sections claires pour les ingrédients, les étapes, les valeurs
    nutritionnelles et les conseils spéciaux.
  expected_output: >
    Code HTML complet pour la recette, avec une mise en page attrayante,
    utilisant des éléments HTML5 et CSS pour une présentation professionnelle.
    La page doit être ENTIÈREMENT en français (pas d'anglais) et peut contenir des emojis.
    Le titre ne doit contenir que le nom de la recette {recipe_name}.
    IMPORTANT: La page ne doit ABSOLUMENT PAS contenir de délimiteurs markdown comme ``` ou ```html, sans '```'.
    Le fichier doit contenir UNIQUEMENT le code HTML pur, sans aucun autre balisage ou commentaire.
  agent: specialized_writer
  output_file: "{recipe_html_path}"

paprika_creation:
  description: >
    Créer une version yaml importable par Paprika 3 de la recette {recipe_name}
    avec un format optimisé pour l'application de cuisine Paprika.
    IMPORTANT: Le fichier ne doit ABSOLUMENT PAS contenir de délimiteurs markdown
    comme ```yaml au début ou ``` à la fin, sans '```'. Le fichier doit contenir UNIQUEMENT
    le contenu YAML brut sans aucun autre balisage ou commentaire.
    Le nom doit contenir que le nom de la recette {recipe_name}.
    TOUTE la recette doit être ENTIÈREMENT en français, y compris les instructions et commentaires.

    Paprika donne comme exemple de recette.

    name: My Tasty Recipe
    servings: 4-6 servings
    source: Food Network
    source_url: http://www.google.com
    prep_time: 10 min
    cook_time: 30 min
    on_favorites: yes
    categories: [Dinner, Holiday]
    nutritional_info: 500 calories
    difficulty: Easy
    rating: 5
    notes: |
      This is delicious!!!
    photo: (base-64 encoded image)
    ingredients: |
      1/2 lb meat
      1/2 lb vegetables
      salt
      pepper
      2 tbsp olive oil
      4 cups flour
    directions: |
      Mix things together.
      Eat.
      Tasty.
      Yum yum yum.

  expected_output: >
    Le ficher yaml brut, sans AUCUN délimiteur markdown (pas de ```yaml ni de ```),
    sans aucune autre information ou aucun autre contenu supplémentaire, sans '```'
    Le fichier doit être ENTIÈREMENT en français et directement importable dans Paprika.
  agent: specialized_writer
  output_file: "{recipe_yaml_path}"

ingredient_list:
  description: >
    À partir de la recette finale pour {recipe_name}  , générer une liste JSON
    structurée de tous les ingrédients nécessaires avec leurs quantités.
    Chaque ingrédient doit inclure nom, quantité et unité de mesure.
  expected_output: >
    Liste JSON des ingrédients au format: [{"name": "nom_ingrédient",
    "quantity": valeur, "unit": "unité"}].
    IMPORTANT: Le fichier doit contenir UNIQUEMENT le JSON brut, sans AUCUN délimiteur
    markdown comme ```json au début ou ``` à la fin, sans '```'
    . Les noms d'ingrédients et unités doivent
    être ENTIÈREMENT en français.
  agent: recipe_expert
  output_file: "{recipe_ingredients_path}"