write_poem:
  description: >
    Write a poem about how CrewAI is awesome.
    Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A beautifully crafted poem about CrewAI, with exactly {sentence_count} sentences.
  agent: poem_writer

write_nutrition:
  description: >
    Génère un fait amusant ou un court poème sur la nutrition adapté aux enfants de {children_age} ans.
    Utiliser un ton ludique et inclure une information nutritionnelle factuelle.
  expected_output: >
    Un fait nutritif ou un poème de quelques lignes, compréhensible et amusant pour un enfant en francais.
  agent: nutrition_writer
